### ISSUE TITLE
Problem handling empty list after an update

### ISSUE THREAD

**Issue by remyleone** [crossplane/terrajet#229]
### What happened?

```yaml
apiVersion: vpc.scaleway.jet.crossplane.io/v1alpha1
kind: PrivateNetwork
metadata:
  name: foobar
spec:
  forProvider:
    name: hello-crossplane
    tags:
      - hello
      - world
  providerConfigRef:
    name: default
```

Everything runs fine and the private network is created. Later on I try to remove the tags field:

```yaml
apiVersion: vpc.scaleway.jet.crossplane.io/v1alpha1
kind: PrivateNetwork
metadata:
  name: foobar
spec:
  forProvider:
    name: hello-crossplane
  providerConfigRef:
    name: default
```

The apply and reconciliation seems to happen but the tags stay on the resource. I've verified using terraform and when I delete the tags in terraform they are effectively deleted after an apply. Maybe there is an issue in update generation in the case of empty list?
