### ISSUE TITLE
Document "ExactlyOneOf" Behavior and interaction with Sensitive fields

### ISSUE THREAD

**Issue by AaronME** [crossplane/terrajet#259]
### What happened?
We attempted to implement `ExactlyOneOf` for a set of fields in our Resource. After `make generate`, both fields in the ExactlyOneOf list were marked as "required."

We are not clear on the desired behavior of setting this field. Does OpenApiV3Schema support `ExactlyOneOf` validation?

### How can we reproduce it?
We added two fields to our schema:

```golang
		r.TerraformResource.Schema["data_string"] = &schema.Schema{
			Type:         schema.TypeString,
			Sensitive:    true,
			ExactlyOneOf: []string{"data_json", "data_string"},
			Description:  comment.String(),
		}
		r.TerraformResource.Schema["data_json"] = &schema.Schema{
			Type:         schema.TypeString,
			Sensitive:    true,
			ExactlyOneOf: []string{"data_json", "data_string"},
			Description:  comment.String(),
		}
```

After code generation, these fields were both required:
```yaml
                  dataJsonSecretRef:
                    description: JSON-encoded secret data to write.
                    properties:
                      key:
                        description: The key to select.
                        type: string
                      name:
                        description: Name of the secret.
                        type: string
                      namespace:
                        description: Namespace of the secret.
                        type: string
                    required:
                    - key
                    - name
                    - namespace
                    type: object
                  dataStringSecretRef:
                    description: String that will be written as the secret data at
                      the given path.
                    properties:
                      key:
                        description: The key to select.
                        type: string
                      name:
                        description: Name of the secret.
                        type: string
                      namespace:
                        description: Namespace of the secret.
                        type: string
                    required:
                    - key
                    - name
                    - namespace
                    type: object
                required:
                - dataJsonSecretRef
                - dataStringSecretRef
```

Submitting with one field or the other returned validation errors for the missing field.
