### ISSUE TITLE
Support custom functions for data pre-processing

### ISSUE THREAD

**Issue by AaronME** [crossplane/terrajet#260]
### What problem are you facing?
The `vault_generic_secret` resource expects data to be formatted as JSON. It uses the Keys of this json to name secret fields when submitting to vault.

An example Kubernetes Secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
stringData:
  exampleKey: '{"keyone": "valueone", "keytwo":"valuetwo"}'
type: Opaque
```

An example Vault Secret:
```yaml
---
apiVersion: generic.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example-vault-secret
spec:
  forProvider:
    path: "secret/foo"
    dataJsonSecretRef:
      key: exampleKey
      name: example-secret
      namespace: default
```

The resulting secret in vault would look like this:
```bash
$ vault kv get secret/foo

===== Data =====
Key        Value
---        -----
keyone     valueone
keytwo     valuetwo
```

If the secret is not json-formatted, it will fail apply and not be created.

In terraform, there are built-in functions which can re-format data as it is submitted to new resources. In a provider, we would need to perform this re-formatting in the controller.

This creates several issues:
1. json-formatted secrets (such as gcp credentials files) are often intended to be consumed as a string and instead are being decomposed into multiple secret fields.
2. ConnectionDetails which are not json formatted are failing apply.

### How could Terrajet help solve your problem?
Allow injecting formatting logic for certain fields. In this example, we would like to be able to specifying a pre-format function in our `config.go` file. This could be added as "Formatted" option on the TerraformResource Schema:

```golang
    p.AddResourceConfigurator("vault_generic_secret", func(r *config.Resource) {
        r.Formatted = config.Formatted {
          "data_json": {
				FormatFn: jsonFormat(data),
        }
    }
```

This would result would appear in the deepCopyInto method for parameters:
```golang
func (in *SecretParameters) DeepCopyInto(out *SecretParameters) {
	*out = *in
	if in.DataJSONSecretRef != nil {
		in, out := &in.DataJSONSecretRef, &out.DataJSONSecretRef
		*out = new(v1.SecretKeySelector)
		**out = jsonFormat(**in)
	}
...
```
